name: simon_pkl
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  easy_splash_screen: ^1.0.4
  persistent_bottom_nav_bar: ^6.2.1
  hugeicons: ^0.0.7
  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^7.0.7296
  icons_launcher: ^2.1.7
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  http: ^1.2.2
  photo_view: ^0.15.0
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.3.0
  open_file: ^3.5.3
  intl: ^0.19.0
  badges: ^3.1.2
  location: ^6.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/logo/LogoSIMON.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  assets:
  - assets/logo/
  - assets/images/
  - assets/icons/
  uses-material-design: true

